services:
  http:
    image: nginx:latest
    ports:
      - 9090:80
    volumes:
      - ./data:/usr/share/nginx/html

  minio:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=uio
      - MINIO_SCHEME=http
      - BITNAMI_DEBUG=true
    volumes:
      - minio_data:/bitnami/minio/data

volumes:
  rabbitmq_data:
  rabbitmq_log:
  minio_data: